-- =============================================================
-- SeriAgent by Fingerprint
-- Oracle ONE AI Immersion 2026
-- Full Database Setup Script
-- Run this in: SQL Workshop > SQL Scripts > Create > Paste > Run
-- =============================================================


-- -------------------------------------------------------------
-- TABLE 1: ORDERS (already created - skip if exists)
-- -------------------------------------------------------------
CREATE TABLE fingerprint_orders (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_name     VARCHAR2(100) NOT NULL,
    project_name    VARCHAR2(100),
    product_type    VARCHAR2(50),
    quantity        NUMBER,
    ink_colors      NUMBER,
    status          VARCHAR2(20) CHECK (status IN ('Pending', 'In Progress', 'Completed', 'Delivered')),
    order_date      DATE DEFAULT SYSDATE
);


-- -------------------------------------------------------------
-- TABLE 2: CLIENTS
-- Stores contact info for each client (e.g., Murillo Autoservicio)
-- -------------------------------------------------------------
CREATE TABLE fingerprint_clients (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_name     VARCHAR2(100) NOT NULL,
    contact_name    VARCHAR2(100),
    phone           VARCHAR2(30),
    email           VARCHAR2(100),
    city            VARCHAR2(50) DEFAULT 'Asunción',
    notes           VARCHAR2(500),
    created_date    DATE DEFAULT SYSDATE
);


-- -------------------------------------------------------------
-- TABLE 3: MATERIALS / INVENTORY
-- Tracks ink, screens, emulsion, and other supplies
-- -------------------------------------------------------------
CREATE TABLE fingerprint_materials (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_name   VARCHAR2(100) NOT NULL,
    category        VARCHAR2(50) CHECK (category IN ('Ink', 'Screen', 'Emulsion', 'Squeegee', 'Substrate', 'Other')),
    unit            VARCHAR2(20),
    stock_quantity  NUMBER DEFAULT 0,
    reorder_level   NUMBER DEFAULT 5,
    unit_cost       NUMBER(10,2),
    supplier        VARCHAR2(100),
    last_updated    DATE DEFAULT SYSDATE
);


-- -------------------------------------------------------------
-- TABLE 4: KNOWLEDGE BASE (for RAG / AI Vector Search)
-- Store screen printing guides, FAQs, and technical notes
-- The AI will search this table to answer user questions
-- -------------------------------------------------------------
CREATE TABLE fingerprint_knowledge (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_title       VARCHAR2(200) NOT NULL,
    category        VARCHAR2(50) CHECK (category IN ('Mesh Guide', 'Ink Types', 'Troubleshooting', 'Safety', 'FAQ', 'Pricing', 'Other')),
    content_text    CLOB,
    source_file     VARCHAR2(200),
    date_added      DATE DEFAULT SYSDATE
);


-- =============================================================
-- SAMPLE DATA
-- =============================================================

BEGIN

    -- CLIENTS
    INSERT INTO fingerprint_clients (client_name, contact_name, phone, email, city, notes)
    VALUES ('Murillo Autoservicio', 'Carlos Murillo', '0981-111-222', 'murillo@auto.com.py', 'Asunción', 'Regular client. Prefers canvas totes with 1-color prints.');

    INSERT INTO fingerprint_clients (client_name, contact_name, phone, email, city, notes)
    VALUES ('Lumen School', 'Admin Office', '021-333-444', 'admin@lumen.edu.py', 'Asunción', 'School uniforms and event shirts. Usually 2-color.');

    INSERT INTO fingerprint_clients (client_name, contact_name, phone, email, city, notes)
    VALUES ('Fingerprint Internal', 'Katherine J.', '0991-555-666', 'katherine@fingerprint.com.py', 'Asunción', 'Internal projects and samples.');

    -- ORDERS
    INSERT INTO fingerprint_orders (client_name, project_name, product_type, quantity, ink_colors, status)
    VALUES ('Murillo Autoservicio', 'Canvas Tote Launch', 'Tote Bag', 50, 1, 'In Progress');

    INSERT INTO fingerprint_orders (client_name, project_name, product_type, quantity, ink_colors, status)
    VALUES ('Lumen School', 'Forensic Science Week', 'T-Shirt', 120, 2, 'Pending');

    INSERT INTO fingerprint_orders (client_name, project_name, product_type, quantity, ink_colors, status)
    VALUES ('Fingerprint Internal', 'Logo Stickers', 'Sticker', 200, 3, 'Completed');

    -- MATERIALS
    INSERT INTO fingerprint_materials (material_name, category, unit, stock_quantity, reorder_level, unit_cost, supplier)
    VALUES ('White Plastisol Ink', 'Ink', 'kg', 3, 2, 45000, 'Gráfica Total PY');

    INSERT INTO fingerprint_materials (material_name, category, unit, stock_quantity, reorder_level, unit_cost, supplier)
    VALUES ('Black Water-Based Ink', 'Ink', 'kg', 5, 2, 38000, 'Gráfica Total PY');

    INSERT INTO fingerprint_materials (material_name, category, unit, stock_quantity, reorder_level, unit_cost, supplier)
    VALUES ('120-Mesh Screen Frame', 'Screen', 'unit', 8, 3, 85000, 'SeriSupply ASU');

    INSERT INTO fingerprint_materials (material_name, category, unit, stock_quantity, reorder_level, unit_cost, supplier)
    VALUES ('Photopolymer Emulsion', 'Emulsion', 'liter', 2, 1, 95000, 'SeriSupply ASU');

    INSERT INTO fingerprint_materials (material_name, category, unit, stock_quantity, reorder_level, unit_cost, supplier)
    VALUES ('Natural Canvas Tote Bag', 'Substrate', 'unit', 150, 50, 12000, 'Telas Asunción');

    -- KNOWLEDGE BASE (starter entries for RAG)
    INSERT INTO fingerprint_knowledge (doc_title, category, content_text, source_file)
    VALUES (
        'Mesh Count Guide for Tote Bags',
        'Mesh Guide',
        'For printing on natural canvas tote bags, use a 110 to 120 mesh count (43T to 48T). This allows a thick ink deposit for good opacity. For fine detail on the same bag, use 150 to 160 mesh. Always use a white base layer on dark or unbleached canvas before applying top colors. Flash-dry between each color at 110°C for 5 seconds.',
        'mesh_guide_v1.txt'
    );

    INSERT INTO fingerprint_knowledge (doc_title, category, content_text, source_file)
    VALUES (
        'Ink Bleeding Troubleshooting',
        'Troubleshooting',
        'Ink bleeding (ink spreading beyond the design edge) is usually caused by: 1) Too much ink pressure from the squeegee — reduce pressure. 2) Ink viscosity too low — add a small amount of curable reducer. 3) Off-contact distance too small — increase the gap between screen and substrate to at least 3mm. 4) Screen mesh too coarse for the design detail — switch to a higher mesh count.',
        'troubleshooting_guide_v1.txt'
    );

    INSERT INTO fingerprint_knowledge (doc_title, category, content_text, source_file)
    VALUES (
        'Ink Washing Off After Laundry',
        'Troubleshooting',
        'If ink washes off after the first laundry cycle, the cure is incomplete. Plastisol ink requires a minimum of 160°C (320°F) throughout the entire ink layer for at least 60 seconds in a conveyor dryer. Use a donut probe thermometer to verify the ink temperature, not just the air temperature. Water-based inks require 170°C for 90 seconds. After curing, the print should not be tacky and should stretch slightly without cracking.',
        'curing_guide_v1.txt'
    );

    INSERT INTO fingerprint_knowledge (doc_title, category, content_text, source_file)
    VALUES (
        'Pricing Formula for Tote Bags',
        'Pricing',
        'Base pricing for canvas tote bags: Cost = (ink_cost_per_unit + substrate_cost + overhead) * margin. For 1-color on canvas: substrate Gs. 12,000 + ink Gs. 1,500 + overhead Gs. 3,000 = Gs. 16,500 cost. Suggested sale price at 2.5x margin = Gs. 41,250. For 2-color: add Gs. 2,500 per additional color. For rush orders (less than 48 hours): add 25% surcharge.',
        'pricing_formula_v1.txt'
    );

    COMMIT;

END;
/

-- =============================================================
-- VERIFY YOUR DATA
-- Run each SELECT separately in SQL Commands to check
-- =============================================================

-- SELECT * FROM fingerprint_clients;
-- SELECT * FROM fingerprint_orders;
-- SELECT * FROM fingerprint_materials;
-- SELECT * FROM fingerprint_knowledge;
